# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 642)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton1 = QtGui.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(90, 30, 50, 50))
        self.pushButton1.setText(_fromUtf8(""))
        self.pushButton1.setCheckable(True)
        self.pushButton1.setChecked(False)
        self.pushButton1.setAutoExclusive(False)
        self.pushButton1.setAutoDefault(False)
        self.pushButton1.setDefault(False)
        self.pushButton1.setFlat(False)
        self.pushButton1.setObjectName(_fromUtf8("pushButton1"))
        self.pushButton2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(140, 30, 50, 50))
        self.pushButton2.setText(_fromUtf8(""))
        self.pushButton2.setCheckable(True)
        self.pushButton2.setChecked(False)
        self.pushButton2.setAutoExclusive(False)
        self.pushButton2.setDefault(False)
        self.pushButton2.setFlat(False)
        self.pushButton2.setObjectName(_fromUtf8("pushButton2"))
        self.pushButton3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(190, 30, 50, 50))
        self.pushButton3.setText(_fromUtf8(""))
        self.pushButton3.setCheckable(True)
        self.pushButton3.setChecked(False)
        self.pushButton3.setAutoExclusive(False)
        self.pushButton3.setDefault(False)
        self.pushButton3.setFlat(False)
        self.pushButton3.setObjectName(_fromUtf8("pushButton3"))
        self.pushButton4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(240, 30, 50, 50))
        self.pushButton4.setText(_fromUtf8(""))
        self.pushButton4.setCheckable(True)
        self.pushButton4.setChecked(False)
        self.pushButton4.setAutoExclusive(False)
        self.pushButton4.setDefault(False)
        self.pushButton4.setFlat(False)
        self.pushButton4.setObjectName(_fromUtf8("pushButton4"))
        self.pushButton5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton5.setGeometry(QtCore.QRect(290, 30, 50, 50))
        self.pushButton5.setText(_fromUtf8(""))
        self.pushButton5.setCheckable(True)
        self.pushButton5.setChecked(False)
        self.pushButton5.setAutoExclusive(False)
        self.pushButton5.setDefault(False)
        self.pushButton5.setFlat(False)
        self.pushButton5.setObjectName(_fromUtf8("pushButton5"))
        self.pushButton6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton6.setGeometry(QtCore.QRect(90, 80, 50, 50))
        self.pushButton6.setText(_fromUtf8(""))
        self.pushButton6.setCheckable(True)
        self.pushButton6.setChecked(False)
        self.pushButton6.setAutoExclusive(False)
        self.pushButton6.setDefault(False)
        self.pushButton6.setFlat(False)
        self.pushButton6.setObjectName(_fromUtf8("pushButton6"))
        self.pushButton10 = QtGui.QPushButton(self.centralwidget)
        self.pushButton10.setGeometry(QtCore.QRect(290, 80, 50, 50))
        self.pushButton10.setText(_fromUtf8(""))
        self.pushButton10.setCheckable(True)
        self.pushButton10.setChecked(False)
        self.pushButton10.setAutoExclusive(False)
        self.pushButton10.setDefault(False)
        self.pushButton10.setFlat(False)
        self.pushButton10.setObjectName(_fromUtf8("pushButton10"))
        self.pushButton7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton7.setGeometry(QtCore.QRect(140, 80, 50, 50))
        self.pushButton7.setText(_fromUtf8(""))
        self.pushButton7.setCheckable(True)
        self.pushButton7.setChecked(False)
        self.pushButton7.setAutoExclusive(False)
        self.pushButton7.setDefault(False)
        self.pushButton7.setFlat(False)
        self.pushButton7.setObjectName(_fromUtf8("pushButton7"))
        self.pushButton8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton8.setGeometry(QtCore.QRect(190, 80, 50, 50))
        self.pushButton8.setText(_fromUtf8(""))
        self.pushButton8.setCheckable(True)
        self.pushButton8.setChecked(False)
        self.pushButton8.setAutoExclusive(False)
        self.pushButton8.setDefault(False)
        self.pushButton8.setFlat(False)
        self.pushButton8.setObjectName(_fromUtf8("pushButton8"))
        self.pushButton9 = QtGui.QPushButton(self.centralwidget)
        self.pushButton9.setGeometry(QtCore.QRect(240, 80, 50, 50))
        self.pushButton9.setText(_fromUtf8(""))
        self.pushButton9.setCheckable(True)
        self.pushButton9.setChecked(False)
        self.pushButton9.setAutoExclusive(False)
        self.pushButton9.setDefault(False)
        self.pushButton9.setFlat(False)
        self.pushButton9.setObjectName(_fromUtf8("pushButton9"))
        self.pushButton11 = QtGui.QPushButton(self.centralwidget)
        self.pushButton11.setGeometry(QtCore.QRect(90, 130, 50, 50))
        self.pushButton11.setText(_fromUtf8(""))
        self.pushButton11.setCheckable(True)
        self.pushButton11.setChecked(False)
        self.pushButton11.setAutoExclusive(False)
        self.pushButton11.setDefault(False)
        self.pushButton11.setFlat(False)
        self.pushButton11.setObjectName(_fromUtf8("pushButton11"))
        self.pushButton15 = QtGui.QPushButton(self.centralwidget)
        self.pushButton15.setGeometry(QtCore.QRect(290, 130, 50, 50))
        self.pushButton15.setText(_fromUtf8(""))
        self.pushButton15.setCheckable(True)
        self.pushButton15.setChecked(False)
        self.pushButton15.setAutoExclusive(False)
        self.pushButton15.setAutoDefault(False)
        self.pushButton15.setDefault(False)
        self.pushButton15.setFlat(False)
        self.pushButton15.setObjectName(_fromUtf8("pushButton15"))
        self.pushButton12 = QtGui.QPushButton(self.centralwidget)
        self.pushButton12.setGeometry(QtCore.QRect(140, 130, 50, 50))
        self.pushButton12.setText(_fromUtf8(""))
        self.pushButton12.setCheckable(True)
        self.pushButton12.setChecked(False)
        self.pushButton12.setAutoExclusive(False)
        self.pushButton12.setDefault(False)
        self.pushButton12.setFlat(False)
        self.pushButton12.setObjectName(_fromUtf8("pushButton12"))
        self.pushButton13 = QtGui.QPushButton(self.centralwidget)
        self.pushButton13.setGeometry(QtCore.QRect(190, 130, 50, 50))
        self.pushButton13.setText(_fromUtf8(""))
        self.pushButton13.setCheckable(True)
        self.pushButton13.setChecked(False)
        self.pushButton13.setAutoExclusive(False)
        self.pushButton13.setDefault(False)
        self.pushButton13.setFlat(False)
        self.pushButton13.setObjectName(_fromUtf8("pushButton13"))
        self.pushButton14 = QtGui.QPushButton(self.centralwidget)
        self.pushButton14.setGeometry(QtCore.QRect(240, 130, 50, 50))
        self.pushButton14.setText(_fromUtf8(""))
        self.pushButton14.setCheckable(True)
        self.pushButton14.setChecked(False)
        self.pushButton14.setAutoExclusive(False)
        self.pushButton14.setDefault(False)
        self.pushButton14.setFlat(False)
        self.pushButton14.setObjectName(_fromUtf8("pushButton14"))
        self.pushButton16 = QtGui.QPushButton(self.centralwidget)
        self.pushButton16.setGeometry(QtCore.QRect(90, 180, 50, 50))
        self.pushButton16.setText(_fromUtf8(""))
        self.pushButton16.setCheckable(True)
        self.pushButton16.setChecked(False)
        self.pushButton16.setAutoExclusive(False)
        self.pushButton16.setDefault(False)
        self.pushButton16.setFlat(False)
        self.pushButton16.setObjectName(_fromUtf8("pushButton16"))
        self.pushButton20 = QtGui.QPushButton(self.centralwidget)
        self.pushButton20.setGeometry(QtCore.QRect(290, 180, 50, 50))
        self.pushButton20.setText(_fromUtf8(""))
        self.pushButton20.setCheckable(True)
        self.pushButton20.setChecked(False)
        self.pushButton20.setAutoExclusive(False)
        self.pushButton20.setDefault(False)
        self.pushButton20.setFlat(False)
        self.pushButton20.setObjectName(_fromUtf8("pushButton20"))
        self.pushButton17 = QtGui.QPushButton(self.centralwidget)
        self.pushButton17.setGeometry(QtCore.QRect(140, 180, 50, 50))
        self.pushButton17.setText(_fromUtf8(""))
        self.pushButton17.setCheckable(True)
        self.pushButton17.setChecked(False)
        self.pushButton17.setAutoExclusive(False)
        self.pushButton17.setDefault(False)
        self.pushButton17.setFlat(False)
        self.pushButton17.setObjectName(_fromUtf8("pushButton17"))
        self.pushButton18 = QtGui.QPushButton(self.centralwidget)
        self.pushButton18.setGeometry(QtCore.QRect(190, 180, 50, 50))
        self.pushButton18.setText(_fromUtf8(""))
        self.pushButton18.setCheckable(True)
        self.pushButton18.setChecked(False)
        self.pushButton18.setAutoExclusive(False)
        self.pushButton18.setDefault(False)
        self.pushButton18.setFlat(False)
        self.pushButton18.setObjectName(_fromUtf8("pushButton18"))
        self.pushButton19 = QtGui.QPushButton(self.centralwidget)
        self.pushButton19.setGeometry(QtCore.QRect(240, 180, 50, 50))
        self.pushButton19.setText(_fromUtf8(""))
        self.pushButton19.setCheckable(True)
        self.pushButton19.setChecked(False)
        self.pushButton19.setAutoExclusive(False)
        self.pushButton19.setDefault(False)
        self.pushButton19.setFlat(False)
        self.pushButton19.setObjectName(_fromUtf8("pushButton19"))
        self.pushButton21 = QtGui.QPushButton(self.centralwidget)
        self.pushButton21.setGeometry(QtCore.QRect(90, 230, 50, 50))
        self.pushButton21.setText(_fromUtf8(""))
        self.pushButton21.setCheckable(True)
        self.pushButton21.setChecked(False)
        self.pushButton21.setAutoExclusive(False)
        self.pushButton21.setDefault(False)
        self.pushButton21.setFlat(False)
        self.pushButton21.setObjectName(_fromUtf8("pushButton21"))
        self.pushButton25 = QtGui.QPushButton(self.centralwidget)
        self.pushButton25.setGeometry(QtCore.QRect(290, 230, 50, 50))
        self.pushButton25.setText(_fromUtf8(""))
        self.pushButton25.setCheckable(True)
        self.pushButton25.setChecked(False)
        self.pushButton25.setAutoExclusive(False)
        self.pushButton25.setDefault(False)
        self.pushButton25.setFlat(False)
        self.pushButton25.setObjectName(_fromUtf8("pushButton25"))
        self.pushButton22 = QtGui.QPushButton(self.centralwidget)
        self.pushButton22.setGeometry(QtCore.QRect(140, 230, 50, 50))
        self.pushButton22.setText(_fromUtf8(""))
        self.pushButton22.setCheckable(True)
        self.pushButton22.setChecked(False)
        self.pushButton22.setAutoExclusive(False)
        self.pushButton22.setDefault(False)
        self.pushButton22.setFlat(False)
        self.pushButton22.setObjectName(_fromUtf8("pushButton22"))
        self.pushButton23 = QtGui.QPushButton(self.centralwidget)
        self.pushButton23.setGeometry(QtCore.QRect(190, 230, 50, 50))
        self.pushButton23.setText(_fromUtf8(""))
        self.pushButton23.setCheckable(True)
        self.pushButton23.setChecked(False)
        self.pushButton23.setAutoExclusive(False)
        self.pushButton23.setDefault(False)
        self.pushButton23.setFlat(False)
        self.pushButton23.setObjectName(_fromUtf8("pushButton23"))
        self.pushButton24 = QtGui.QPushButton(self.centralwidget)
        self.pushButton24.setGeometry(QtCore.QRect(240, 230, 50, 50))
        self.pushButton24.setText(_fromUtf8(""))
        self.pushButton24.setCheckable(True)
        self.pushButton24.setChecked(False)
        self.pushButton24.setAutoExclusive(False)
        self.pushButton24.setDefault(False)
        self.pushButton24.setFlat(False)
        self.pushButton24.setObjectName(_fromUtf8("pushButton24"))
        self.nauka = QtGui.QPushButton(self.centralwidget)
        self.nauka.setGeometry(QtCore.QRect(240, 550, 99, 27))
        self.nauka.setObjectName(_fromUtf8("nauka"))
        self.zgaduj = QtGui.QPushButton(self.centralwidget)
        self.zgaduj.setGeometry(QtCore.QRect(420, 550, 99, 27))
        self.zgaduj.setObjectName(_fromUtf8("zgaduj"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton4, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton4.setChecked)
        QtCore.QObject.connect(self.pushButton5, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton5.setChecked)
        QtCore.QObject.connect(self.pushButton6, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton6.setChecked)
        QtCore.QObject.connect(self.pushButton7, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton7.setChecked)
        QtCore.QObject.connect(self.pushButton8, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton8.setChecked)
        QtCore.QObject.connect(self.pushButton9, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton9.setChecked)
        QtCore.QObject.connect(self.pushButton10, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton10.setChecked)
        QtCore.QObject.connect(self.pushButton11, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton11.setChecked)
        QtCore.QObject.connect(self.pushButton12, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton12.setChecked)
        QtCore.QObject.connect(self.pushButton13, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton13.setChecked)
        QtCore.QObject.connect(self.pushButton14, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton14.setChecked)
        QtCore.QObject.connect(self.pushButton15, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton15.setChecked)
        QtCore.QObject.connect(self.pushButton16, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton16.setChecked)
        QtCore.QObject.connect(self.pushButton17, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton17.setChecked)
        QtCore.QObject.connect(self.pushButton18, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton18.setChecked)
        QtCore.QObject.connect(self.pushButton19, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton19.setChecked)
        QtCore.QObject.connect(self.pushButton20, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton20.setChecked)
        QtCore.QObject.connect(self.pushButton21, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton21.setChecked)
        QtCore.QObject.connect(self.pushButton22, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton22.setChecked)
        QtCore.QObject.connect(self.pushButton23, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton23.setChecked)
        QtCore.QObject.connect(self.pushButton24, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton24.setChecked)
        QtCore.QObject.connect(self.pushButton25, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton25.setChecked)
        QtCore.QObject.connect(self.pushButton1, QtCore.SIGNAL(_fromUtf8("released()")), self.pushButton1.setFocus)
        QtCore.QObject.connect(self.pushButton2, QtCore.SIGNAL(_fromUtf8("released()")), self.pushButton2.lower)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.nauka.setText(_translate("MainWindow", "Ucz się", None))
        self.zgaduj.setText(_translate("MainWindow", "OK", None))

