# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 642)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton1 = QtGui.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(100, 30, 10, 10))
        self.pushButton1.setText(_fromUtf8(""))
        self.pushButton1.setCheckable(True)
        self.pushButton1.setChecked(False)
        self.pushButton1.setAutoExclusive(False)
        self.pushButton1.setAutoDefault(False)
        self.pushButton1.setDefault(False)
        self.pushButton1.setFlat(False)
        self.pushButton1.setObjectName(_fromUtf8("pushButton1"))
        self.pushButton2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(110, 30, 10, 10))
        self.pushButton2.setText(_fromUtf8(""))
        self.pushButton2.setCheckable(True)
        self.pushButton2.setChecked(False)
        self.pushButton2.setAutoExclusive(False)
        self.pushButton2.setDefault(False)
        self.pushButton2.setFlat(False)
        self.pushButton2.setObjectName(_fromUtf8("pushButton2"))
        self.pushButton3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(120, 30, 10, 10))
        self.pushButton3.setText(_fromUtf8(""))
        self.pushButton3.setCheckable(True)
        self.pushButton3.setChecked(False)
        self.pushButton3.setAutoExclusive(False)
        self.pushButton3.setDefault(False)
        self.pushButton3.setFlat(False)
        self.pushButton3.setObjectName(_fromUtf8("pushButton3"))
        self.pushButton4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(130, 30, 10, 10))
        self.pushButton4.setText(_fromUtf8(""))
        self.pushButton4.setCheckable(True)
        self.pushButton4.setChecked(False)
        self.pushButton4.setAutoExclusive(False)
        self.pushButton4.setDefault(False)
        self.pushButton4.setFlat(False)
        self.pushButton4.setObjectName(_fromUtf8("pushButton4"))
        self.pushButton5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton5.setGeometry(QtCore.QRect(140, 30, 10, 10))
        self.pushButton5.setText(_fromUtf8(""))
        self.pushButton5.setCheckable(True)
        self.pushButton5.setChecked(False)
        self.pushButton5.setAutoExclusive(False)
        self.pushButton5.setDefault(False)
        self.pushButton5.setFlat(False)
        self.pushButton5.setObjectName(_fromUtf8("pushButton5"))
        self.pushButton6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton6.setGeometry(QtCore.QRect(100, 40, 10, 10))
        self.pushButton6.setText(_fromUtf8(""))
        self.pushButton6.setCheckable(True)
        self.pushButton6.setChecked(False)
        self.pushButton6.setAutoExclusive(False)
        self.pushButton6.setDefault(False)
        self.pushButton6.setFlat(False)
        self.pushButton6.setObjectName(_fromUtf8("pushButton6"))
        self.pushButton10 = QtGui.QPushButton(self.centralwidget)
        self.pushButton10.setGeometry(QtCore.QRect(140, 40, 10, 10))
        self.pushButton10.setText(_fromUtf8(""))
        self.pushButton10.setCheckable(True)
        self.pushButton10.setChecked(False)
        self.pushButton10.setAutoExclusive(False)
        self.pushButton10.setDefault(False)
        self.pushButton10.setFlat(False)
        self.pushButton10.setObjectName(_fromUtf8("pushButton10"))
        self.pushButton7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton7.setGeometry(QtCore.QRect(110, 40, 10, 10))
        self.pushButton7.setText(_fromUtf8(""))
        self.pushButton7.setCheckable(True)
        self.pushButton7.setChecked(False)
        self.pushButton7.setAutoExclusive(False)
        self.pushButton7.setDefault(False)
        self.pushButton7.setFlat(False)
        self.pushButton7.setObjectName(_fromUtf8("pushButton7"))
        self.pushButton8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton8.setGeometry(QtCore.QRect(120, 40, 10, 10))
        self.pushButton8.setText(_fromUtf8(""))
        self.pushButton8.setCheckable(True)
        self.pushButton8.setChecked(False)
        self.pushButton8.setAutoExclusive(False)
        self.pushButton8.setDefault(False)
        self.pushButton8.setFlat(False)
        self.pushButton8.setObjectName(_fromUtf8("pushButton8"))
        self.pushButton9 = QtGui.QPushButton(self.centralwidget)
        self.pushButton9.setGeometry(QtCore.QRect(130, 40, 10, 10))
        self.pushButton9.setText(_fromUtf8(""))
        self.pushButton9.setCheckable(True)
        self.pushButton9.setChecked(False)
        self.pushButton9.setAutoExclusive(False)
        self.pushButton9.setDefault(False)
        self.pushButton9.setFlat(False)
        self.pushButton9.setObjectName(_fromUtf8("pushButton9"))
        self.pushButton11 = QtGui.QPushButton(self.centralwidget)
        self.pushButton11.setGeometry(QtCore.QRect(100, 50, 10, 10))
        self.pushButton11.setText(_fromUtf8(""))
        self.pushButton11.setCheckable(True)
        self.pushButton11.setChecked(False)
        self.pushButton11.setAutoExclusive(False)
        self.pushButton11.setDefault(False)
        self.pushButton11.setFlat(False)
        self.pushButton11.setObjectName(_fromUtf8("pushButton11"))
        self.pushButton15 = QtGui.QPushButton(self.centralwidget)
        self.pushButton15.setGeometry(QtCore.QRect(140, 50, 10, 10))
        self.pushButton15.setText(_fromUtf8(""))
        self.pushButton15.setCheckable(True)
        self.pushButton15.setChecked(False)
        self.pushButton15.setAutoExclusive(False)
        self.pushButton15.setAutoDefault(False)
        self.pushButton15.setDefault(False)
        self.pushButton15.setFlat(False)
        self.pushButton15.setObjectName(_fromUtf8("pushButton15"))
        self.pushButton12 = QtGui.QPushButton(self.centralwidget)
        self.pushButton12.setGeometry(QtCore.QRect(110, 50, 10, 10))
        self.pushButton12.setText(_fromUtf8(""))
        self.pushButton12.setCheckable(True)
        self.pushButton12.setChecked(False)
        self.pushButton12.setAutoExclusive(False)
        self.pushButton12.setDefault(False)
        self.pushButton12.setFlat(False)
        self.pushButton12.setObjectName(_fromUtf8("pushButton12"))
        self.pushButton13 = QtGui.QPushButton(self.centralwidget)
        self.pushButton13.setGeometry(QtCore.QRect(120, 50, 10, 10))
        self.pushButton13.setText(_fromUtf8(""))
        self.pushButton13.setCheckable(True)
        self.pushButton13.setChecked(False)
        self.pushButton13.setAutoExclusive(False)
        self.pushButton13.setDefault(False)
        self.pushButton13.setFlat(False)
        self.pushButton13.setObjectName(_fromUtf8("pushButton13"))
        self.pushButton14 = QtGui.QPushButton(self.centralwidget)
        self.pushButton14.setGeometry(QtCore.QRect(130, 50, 10, 10))
        self.pushButton14.setText(_fromUtf8(""))
        self.pushButton14.setCheckable(True)
        self.pushButton14.setChecked(False)
        self.pushButton14.setAutoExclusive(False)
        self.pushButton14.setDefault(False)
        self.pushButton14.setFlat(False)
        self.pushButton14.setObjectName(_fromUtf8("pushButton14"))
        self.pushButton16 = QtGui.QPushButton(self.centralwidget)
        self.pushButton16.setGeometry(QtCore.QRect(100, 60, 10, 10))
        self.pushButton16.setText(_fromUtf8(""))
        self.pushButton16.setCheckable(True)
        self.pushButton16.setChecked(False)
        self.pushButton16.setAutoExclusive(False)
        self.pushButton16.setDefault(False)
        self.pushButton16.setFlat(False)
        self.pushButton16.setObjectName(_fromUtf8("pushButton16"))
        self.pushButton20 = QtGui.QPushButton(self.centralwidget)
        self.pushButton20.setGeometry(QtCore.QRect(140, 60, 10, 10))
        self.pushButton20.setText(_fromUtf8(""))
        self.pushButton20.setCheckable(True)
        self.pushButton20.setChecked(False)
        self.pushButton20.setAutoExclusive(False)
        self.pushButton20.setDefault(False)
        self.pushButton20.setFlat(False)
        self.pushButton20.setObjectName(_fromUtf8("pushButton20"))
        self.pushButton17 = QtGui.QPushButton(self.centralwidget)
        self.pushButton17.setGeometry(QtCore.QRect(110, 60, 10, 10))
        self.pushButton17.setText(_fromUtf8(""))
        self.pushButton17.setCheckable(True)
        self.pushButton17.setChecked(False)
        self.pushButton17.setAutoExclusive(False)
        self.pushButton17.setDefault(False)
        self.pushButton17.setFlat(False)
        self.pushButton17.setObjectName(_fromUtf8("pushButton17"))
        self.pushButton18 = QtGui.QPushButton(self.centralwidget)
        self.pushButton18.setGeometry(QtCore.QRect(120, 60, 10, 10))
        self.pushButton18.setText(_fromUtf8(""))
        self.pushButton18.setCheckable(True)
        self.pushButton18.setChecked(False)
        self.pushButton18.setAutoExclusive(False)
        self.pushButton18.setDefault(False)
        self.pushButton18.setFlat(False)
        self.pushButton18.setObjectName(_fromUtf8("pushButton18"))
        self.pushButton19 = QtGui.QPushButton(self.centralwidget)
        self.pushButton19.setGeometry(QtCore.QRect(130, 60, 10, 10))
        self.pushButton19.setText(_fromUtf8(""))
        self.pushButton19.setCheckable(True)
        self.pushButton19.setChecked(False)
        self.pushButton19.setAutoExclusive(False)
        self.pushButton19.setDefault(False)
        self.pushButton19.setFlat(False)
        self.pushButton19.setObjectName(_fromUtf8("pushButton19"))
        self.pushButton21 = QtGui.QPushButton(self.centralwidget)
        self.pushButton21.setGeometry(QtCore.QRect(100, 70, 10, 10))
        self.pushButton21.setText(_fromUtf8(""))
        self.pushButton21.setCheckable(True)
        self.pushButton21.setChecked(False)
        self.pushButton21.setAutoExclusive(False)
        self.pushButton21.setDefault(False)
        self.pushButton21.setFlat(False)
        self.pushButton21.setObjectName(_fromUtf8("pushButton21"))
        self.pushButton25 = QtGui.QPushButton(self.centralwidget)
        self.pushButton25.setGeometry(QtCore.QRect(140, 70, 10, 10))
        self.pushButton25.setText(_fromUtf8(""))
        self.pushButton25.setCheckable(True)
        self.pushButton25.setChecked(False)
        self.pushButton25.setAutoExclusive(False)
        self.pushButton25.setDefault(False)
        self.pushButton25.setFlat(False)
        self.pushButton25.setObjectName(_fromUtf8("pushButton25"))
        self.pushButton22 = QtGui.QPushButton(self.centralwidget)
        self.pushButton22.setGeometry(QtCore.QRect(110, 70, 10, 10))
        self.pushButton22.setText(_fromUtf8(""))
        self.pushButton22.setCheckable(True)
        self.pushButton22.setChecked(False)
        self.pushButton22.setAutoExclusive(False)
        self.pushButton22.setDefault(False)
        self.pushButton22.setFlat(False)
        self.pushButton22.setObjectName(_fromUtf8("pushButton22"))
        self.pushButton23 = QtGui.QPushButton(self.centralwidget)
        self.pushButton23.setGeometry(QtCore.QRect(120, 70, 10, 10))
        self.pushButton23.setText(_fromUtf8(""))
        self.pushButton23.setCheckable(True)
        self.pushButton23.setChecked(False)
        self.pushButton23.setAutoExclusive(False)
        self.pushButton23.setDefault(False)
        self.pushButton23.setFlat(False)
        self.pushButton23.setObjectName(_fromUtf8("pushButton23"))
        self.pushButton24 = QtGui.QPushButton(self.centralwidget)
        self.pushButton24.setGeometry(QtCore.QRect(130, 70, 10, 10))
        self.pushButton24.setText(_fromUtf8(""))
        self.pushButton24.setCheckable(True)
        self.pushButton24.setChecked(False)
        self.pushButton24.setAutoExclusive(False)
        self.pushButton24.setDefault(False)
        self.pushButton24.setFlat(False)
        self.pushButton24.setObjectName(_fromUtf8("pushButton24"))
        self.nauka = QtGui.QPushButton(self.centralwidget)
        self.nauka.setGeometry(QtCore.QRect(240, 550, 99, 27))
        self.nauka.setObjectName(_fromUtf8("nauka"))
        self.zgaduj = QtGui.QPushButton(self.centralwidget)
        self.zgaduj.setGeometry(QtCore.QRect(420, 550, 99, 27))
        self.zgaduj.setObjectName(_fromUtf8("zgaduj"))
        self.pushButton4_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton4_2.setGeometry(QtCore.QRect(180, 30, 10, 10))
        self.pushButton4_2.setText(_fromUtf8(""))
        self.pushButton4_2.setCheckable(True)
        self.pushButton4_2.setChecked(False)
        self.pushButton4_2.setAutoExclusive(False)
        self.pushButton4_2.setDefault(False)
        self.pushButton4_2.setFlat(False)
        self.pushButton4_2.setObjectName(_fromUtf8("pushButton4_2"))
        self.pushButton18_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton18_2.setGeometry(QtCore.QRect(170, 60, 10, 10))
        self.pushButton18_2.setText(_fromUtf8(""))
        self.pushButton18_2.setCheckable(True)
        self.pushButton18_2.setChecked(False)
        self.pushButton18_2.setAutoExclusive(False)
        self.pushButton18_2.setDefault(False)
        self.pushButton18_2.setFlat(False)
        self.pushButton18_2.setObjectName(_fromUtf8("pushButton18_2"))
        self.pushButton23_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton23_2.setGeometry(QtCore.QRect(170, 70, 10, 10))
        self.pushButton23_2.setText(_fromUtf8(""))
        self.pushButton23_2.setCheckable(True)
        self.pushButton23_2.setChecked(False)
        self.pushButton23_2.setAutoExclusive(False)
        self.pushButton23_2.setDefault(False)
        self.pushButton23_2.setFlat(False)
        self.pushButton23_2.setObjectName(_fromUtf8("pushButton23_2"))
        self.pushButton1_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton1_2.setGeometry(QtCore.QRect(150, 30, 10, 10))
        self.pushButton1_2.setText(_fromUtf8(""))
        self.pushButton1_2.setCheckable(True)
        self.pushButton1_2.setChecked(False)
        self.pushButton1_2.setAutoExclusive(False)
        self.pushButton1_2.setAutoDefault(False)
        self.pushButton1_2.setDefault(False)
        self.pushButton1_2.setFlat(False)
        self.pushButton1_2.setObjectName(_fromUtf8("pushButton1_2"))
        self.pushButton21_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton21_2.setGeometry(QtCore.QRect(150, 70, 10, 10))
        self.pushButton21_2.setText(_fromUtf8(""))
        self.pushButton21_2.setCheckable(True)
        self.pushButton21_2.setChecked(False)
        self.pushButton21_2.setAutoExclusive(False)
        self.pushButton21_2.setDefault(False)
        self.pushButton21_2.setFlat(False)
        self.pushButton21_2.setObjectName(_fromUtf8("pushButton21_2"))
        self.pushButton13_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton13_2.setGeometry(QtCore.QRect(170, 50, 10, 10))
        self.pushButton13_2.setText(_fromUtf8(""))
        self.pushButton13_2.setCheckable(True)
        self.pushButton13_2.setChecked(False)
        self.pushButton13_2.setAutoExclusive(False)
        self.pushButton13_2.setDefault(False)
        self.pushButton13_2.setFlat(False)
        self.pushButton13_2.setObjectName(_fromUtf8("pushButton13_2"))
        self.pushButton15_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton15_2.setGeometry(QtCore.QRect(190, 50, 10, 10))
        self.pushButton15_2.setText(_fromUtf8(""))
        self.pushButton15_2.setCheckable(True)
        self.pushButton15_2.setChecked(False)
        self.pushButton15_2.setAutoExclusive(False)
        self.pushButton15_2.setAutoDefault(False)
        self.pushButton15_2.setDefault(False)
        self.pushButton15_2.setFlat(False)
        self.pushButton15_2.setObjectName(_fromUtf8("pushButton15_2"))
        self.pushButton22_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton22_2.setGeometry(QtCore.QRect(160, 70, 10, 10))
        self.pushButton22_2.setText(_fromUtf8(""))
        self.pushButton22_2.setCheckable(True)
        self.pushButton22_2.setChecked(False)
        self.pushButton22_2.setAutoExclusive(False)
        self.pushButton22_2.setDefault(False)
        self.pushButton22_2.setFlat(False)
        self.pushButton22_2.setObjectName(_fromUtf8("pushButton22_2"))
        self.pushButton8_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton8_2.setGeometry(QtCore.QRect(170, 40, 10, 10))
        self.pushButton8_2.setText(_fromUtf8(""))
        self.pushButton8_2.setCheckable(True)
        self.pushButton8_2.setChecked(False)
        self.pushButton8_2.setAutoExclusive(False)
        self.pushButton8_2.setDefault(False)
        self.pushButton8_2.setFlat(False)
        self.pushButton8_2.setObjectName(_fromUtf8("pushButton8_2"))
        self.pushButton11_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton11_2.setGeometry(QtCore.QRect(150, 50, 10, 10))
        self.pushButton11_2.setText(_fromUtf8(""))
        self.pushButton11_2.setCheckable(True)
        self.pushButton11_2.setChecked(False)
        self.pushButton11_2.setAutoExclusive(False)
        self.pushButton11_2.setDefault(False)
        self.pushButton11_2.setFlat(False)
        self.pushButton11_2.setObjectName(_fromUtf8("pushButton11_2"))
        self.pushButton9_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton9_2.setGeometry(QtCore.QRect(180, 40, 10, 10))
        self.pushButton9_2.setText(_fromUtf8(""))
        self.pushButton9_2.setCheckable(True)
        self.pushButton9_2.setChecked(False)
        self.pushButton9_2.setAutoExclusive(False)
        self.pushButton9_2.setDefault(False)
        self.pushButton9_2.setFlat(False)
        self.pushButton9_2.setObjectName(_fromUtf8("pushButton9_2"))
        self.pushButton20_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton20_2.setGeometry(QtCore.QRect(190, 60, 10, 10))
        self.pushButton20_2.setText(_fromUtf8(""))
        self.pushButton20_2.setCheckable(True)
        self.pushButton20_2.setChecked(False)
        self.pushButton20_2.setAutoExclusive(False)
        self.pushButton20_2.setDefault(False)
        self.pushButton20_2.setFlat(False)
        self.pushButton20_2.setObjectName(_fromUtf8("pushButton20_2"))
        self.pushButton24_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton24_2.setGeometry(QtCore.QRect(180, 70, 10, 10))
        self.pushButton24_2.setText(_fromUtf8(""))
        self.pushButton24_2.setCheckable(True)
        self.pushButton24_2.setChecked(False)
        self.pushButton24_2.setAutoExclusive(False)
        self.pushButton24_2.setDefault(False)
        self.pushButton24_2.setFlat(False)
        self.pushButton24_2.setObjectName(_fromUtf8("pushButton24_2"))
        self.pushButton2_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton2_2.setGeometry(QtCore.QRect(160, 30, 10, 10))
        self.pushButton2_2.setText(_fromUtf8(""))
        self.pushButton2_2.setCheckable(True)
        self.pushButton2_2.setChecked(False)
        self.pushButton2_2.setAutoExclusive(False)
        self.pushButton2_2.setDefault(False)
        self.pushButton2_2.setFlat(False)
        self.pushButton2_2.setObjectName(_fromUtf8("pushButton2_2"))
        self.pushButton25_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton25_2.setGeometry(QtCore.QRect(190, 70, 10, 10))
        self.pushButton25_2.setText(_fromUtf8(""))
        self.pushButton25_2.setCheckable(True)
        self.pushButton25_2.setChecked(False)
        self.pushButton25_2.setAutoExclusive(False)
        self.pushButton25_2.setDefault(False)
        self.pushButton25_2.setFlat(False)
        self.pushButton25_2.setObjectName(_fromUtf8("pushButton25_2"))
        self.pushButton19_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton19_2.setGeometry(QtCore.QRect(180, 60, 10, 10))
        self.pushButton19_2.setText(_fromUtf8(""))
        self.pushButton19_2.setCheckable(True)
        self.pushButton19_2.setChecked(False)
        self.pushButton19_2.setAutoExclusive(False)
        self.pushButton19_2.setDefault(False)
        self.pushButton19_2.setFlat(False)
        self.pushButton19_2.setObjectName(_fromUtf8("pushButton19_2"))
        self.pushButton6_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton6_2.setGeometry(QtCore.QRect(150, 40, 10, 10))
        self.pushButton6_2.setText(_fromUtf8(""))
        self.pushButton6_2.setCheckable(True)
        self.pushButton6_2.setChecked(False)
        self.pushButton6_2.setAutoExclusive(False)
        self.pushButton6_2.setDefault(False)
        self.pushButton6_2.setFlat(False)
        self.pushButton6_2.setObjectName(_fromUtf8("pushButton6_2"))
        self.pushButton5_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton5_2.setGeometry(QtCore.QRect(190, 30, 10, 10))
        self.pushButton5_2.setText(_fromUtf8(""))
        self.pushButton5_2.setCheckable(True)
        self.pushButton5_2.setChecked(False)
        self.pushButton5_2.setAutoExclusive(False)
        self.pushButton5_2.setDefault(False)
        self.pushButton5_2.setFlat(False)
        self.pushButton5_2.setObjectName(_fromUtf8("pushButton5_2"))
        self.pushButton3_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton3_2.setGeometry(QtCore.QRect(170, 30, 10, 10))
        self.pushButton3_2.setText(_fromUtf8(""))
        self.pushButton3_2.setCheckable(True)
        self.pushButton3_2.setChecked(False)
        self.pushButton3_2.setAutoExclusive(False)
        self.pushButton3_2.setDefault(False)
        self.pushButton3_2.setFlat(False)
        self.pushButton3_2.setObjectName(_fromUtf8("pushButton3_2"))
        self.pushButton16_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton16_2.setGeometry(QtCore.QRect(150, 60, 10, 10))
        self.pushButton16_2.setText(_fromUtf8(""))
        self.pushButton16_2.setCheckable(True)
        self.pushButton16_2.setChecked(False)
        self.pushButton16_2.setAutoExclusive(False)
        self.pushButton16_2.setDefault(False)
        self.pushButton16_2.setFlat(False)
        self.pushButton16_2.setObjectName(_fromUtf8("pushButton16_2"))
        self.pushButton14_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton14_2.setGeometry(QtCore.QRect(180, 50, 10, 10))
        self.pushButton14_2.setText(_fromUtf8(""))
        self.pushButton14_2.setCheckable(True)
        self.pushButton14_2.setChecked(False)
        self.pushButton14_2.setAutoExclusive(False)
        self.pushButton14_2.setDefault(False)
        self.pushButton14_2.setFlat(False)
        self.pushButton14_2.setObjectName(_fromUtf8("pushButton14_2"))
        self.pushButton10_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton10_2.setGeometry(QtCore.QRect(190, 40, 10, 10))
        self.pushButton10_2.setText(_fromUtf8(""))
        self.pushButton10_2.setCheckable(True)
        self.pushButton10_2.setChecked(False)
        self.pushButton10_2.setAutoExclusive(False)
        self.pushButton10_2.setDefault(False)
        self.pushButton10_2.setFlat(False)
        self.pushButton10_2.setObjectName(_fromUtf8("pushButton10_2"))
        self.pushButton12_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton12_2.setGeometry(QtCore.QRect(160, 50, 10, 10))
        self.pushButton12_2.setText(_fromUtf8(""))
        self.pushButton12_2.setCheckable(True)
        self.pushButton12_2.setChecked(False)
        self.pushButton12_2.setAutoExclusive(False)
        self.pushButton12_2.setDefault(False)
        self.pushButton12_2.setFlat(False)
        self.pushButton12_2.setObjectName(_fromUtf8("pushButton12_2"))
        self.pushButton7_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton7_2.setGeometry(QtCore.QRect(160, 40, 10, 10))
        self.pushButton7_2.setText(_fromUtf8(""))
        self.pushButton7_2.setCheckable(True)
        self.pushButton7_2.setChecked(False)
        self.pushButton7_2.setAutoExclusive(False)
        self.pushButton7_2.setDefault(False)
        self.pushButton7_2.setFlat(False)
        self.pushButton7_2.setObjectName(_fromUtf8("pushButton7_2"))
        self.pushButton17_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton17_2.setGeometry(QtCore.QRect(160, 60, 10, 10))
        self.pushButton17_2.setText(_fromUtf8(""))
        self.pushButton17_2.setCheckable(True)
        self.pushButton17_2.setChecked(False)
        self.pushButton17_2.setAutoExclusive(False)
        self.pushButton17_2.setDefault(False)
        self.pushButton17_2.setFlat(False)
        self.pushButton17_2.setObjectName(_fromUtf8("pushButton17_2"))
        self.pushButton15_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton15_3.setGeometry(QtCore.QRect(140, 100, 10, 10))
        self.pushButton15_3.setText(_fromUtf8(""))
        self.pushButton15_3.setCheckable(True)
        self.pushButton15_3.setChecked(False)
        self.pushButton15_3.setAutoExclusive(False)
        self.pushButton15_3.setAutoDefault(False)
        self.pushButton15_3.setDefault(False)
        self.pushButton15_3.setFlat(False)
        self.pushButton15_3.setObjectName(_fromUtf8("pushButton15_3"))
        self.pushButton8_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton8_3.setGeometry(QtCore.QRect(120, 90, 10, 10))
        self.pushButton8_3.setText(_fromUtf8(""))
        self.pushButton8_3.setCheckable(True)
        self.pushButton8_3.setChecked(False)
        self.pushButton8_3.setAutoExclusive(False)
        self.pushButton8_3.setDefault(False)
        self.pushButton8_3.setFlat(False)
        self.pushButton8_3.setObjectName(_fromUtf8("pushButton8_3"))
        self.pushButton1_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton1_3.setGeometry(QtCore.QRect(150, 80, 10, 10))
        self.pushButton1_3.setText(_fromUtf8(""))
        self.pushButton1_3.setCheckable(True)
        self.pushButton1_3.setChecked(False)
        self.pushButton1_3.setAutoExclusive(False)
        self.pushButton1_3.setAutoDefault(False)
        self.pushButton1_3.setDefault(False)
        self.pushButton1_3.setFlat(False)
        self.pushButton1_3.setObjectName(_fromUtf8("pushButton1_3"))
        self.pushButton6_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton6_3.setGeometry(QtCore.QRect(150, 90, 10, 10))
        self.pushButton6_3.setText(_fromUtf8(""))
        self.pushButton6_3.setCheckable(True)
        self.pushButton6_3.setChecked(False)
        self.pushButton6_3.setAutoExclusive(False)
        self.pushButton6_3.setDefault(False)
        self.pushButton6_3.setFlat(False)
        self.pushButton6_3.setObjectName(_fromUtf8("pushButton6_3"))
        self.pushButton17_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton17_3.setGeometry(QtCore.QRect(110, 110, 10, 10))
        self.pushButton17_3.setText(_fromUtf8(""))
        self.pushButton17_3.setCheckable(True)
        self.pushButton17_3.setChecked(False)
        self.pushButton17_3.setAutoExclusive(False)
        self.pushButton17_3.setDefault(False)
        self.pushButton17_3.setFlat(False)
        self.pushButton17_3.setObjectName(_fromUtf8("pushButton17_3"))
        self.pushButton2_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton2_3.setGeometry(QtCore.QRect(160, 80, 10, 10))
        self.pushButton2_3.setText(_fromUtf8(""))
        self.pushButton2_3.setCheckable(True)
        self.pushButton2_3.setChecked(False)
        self.pushButton2_3.setAutoExclusive(False)
        self.pushButton2_3.setDefault(False)
        self.pushButton2_3.setFlat(False)
        self.pushButton2_3.setObjectName(_fromUtf8("pushButton2_3"))
        self.pushButton7_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton7_3.setGeometry(QtCore.QRect(110, 90, 10, 10))
        self.pushButton7_3.setText(_fromUtf8(""))
        self.pushButton7_3.setCheckable(True)
        self.pushButton7_3.setChecked(False)
        self.pushButton7_3.setAutoExclusive(False)
        self.pushButton7_3.setDefault(False)
        self.pushButton7_3.setFlat(False)
        self.pushButton7_3.setObjectName(_fromUtf8("pushButton7_3"))
        self.pushButton12_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton12_3.setGeometry(QtCore.QRect(160, 100, 10, 10))
        self.pushButton12_3.setText(_fromUtf8(""))
        self.pushButton12_3.setCheckable(True)
        self.pushButton12_3.setChecked(False)
        self.pushButton12_3.setAutoExclusive(False)
        self.pushButton12_3.setDefault(False)
        self.pushButton12_3.setFlat(False)
        self.pushButton12_3.setObjectName(_fromUtf8("pushButton12_3"))
        self.pushButton23_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton23_3.setGeometry(QtCore.QRect(120, 120, 10, 10))
        self.pushButton23_3.setText(_fromUtf8(""))
        self.pushButton23_3.setCheckable(True)
        self.pushButton23_3.setChecked(False)
        self.pushButton23_3.setAutoExclusive(False)
        self.pushButton23_3.setDefault(False)
        self.pushButton23_3.setFlat(False)
        self.pushButton23_3.setObjectName(_fromUtf8("pushButton23_3"))
        self.pushButton18_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton18_3.setGeometry(QtCore.QRect(120, 110, 10, 10))
        self.pushButton18_3.setText(_fromUtf8(""))
        self.pushButton18_3.setCheckable(True)
        self.pushButton18_3.setChecked(False)
        self.pushButton18_3.setAutoExclusive(False)
        self.pushButton18_3.setDefault(False)
        self.pushButton18_3.setFlat(False)
        self.pushButton18_3.setObjectName(_fromUtf8("pushButton18_3"))
        self.pushButton24_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton24_3.setGeometry(QtCore.QRect(130, 120, 10, 10))
        self.pushButton24_3.setText(_fromUtf8(""))
        self.pushButton24_3.setCheckable(True)
        self.pushButton24_3.setChecked(False)
        self.pushButton24_3.setAutoExclusive(False)
        self.pushButton24_3.setDefault(False)
        self.pushButton24_3.setFlat(False)
        self.pushButton24_3.setObjectName(_fromUtf8("pushButton24_3"))
        self.pushButton20_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton20_3.setGeometry(QtCore.QRect(190, 110, 10, 10))
        self.pushButton20_3.setText(_fromUtf8(""))
        self.pushButton20_3.setCheckable(True)
        self.pushButton20_3.setChecked(False)
        self.pushButton20_3.setAutoExclusive(False)
        self.pushButton20_3.setDefault(False)
        self.pushButton20_3.setFlat(False)
        self.pushButton20_3.setObjectName(_fromUtf8("pushButton20_3"))
        self.pushButton11_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton11_3.setGeometry(QtCore.QRect(100, 100, 10, 10))
        self.pushButton11_3.setText(_fromUtf8(""))
        self.pushButton11_3.setCheckable(True)
        self.pushButton11_3.setChecked(False)
        self.pushButton11_3.setAutoExclusive(False)
        self.pushButton11_3.setDefault(False)
        self.pushButton11_3.setFlat(False)
        self.pushButton11_3.setObjectName(_fromUtf8("pushButton11_3"))
        self.pushButton13_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton13_3.setGeometry(QtCore.QRect(120, 100, 10, 10))
        self.pushButton13_3.setText(_fromUtf8(""))
        self.pushButton13_3.setCheckable(True)
        self.pushButton13_3.setChecked(False)
        self.pushButton13_3.setAutoExclusive(False)
        self.pushButton13_3.setDefault(False)
        self.pushButton13_3.setFlat(False)
        self.pushButton13_3.setObjectName(_fromUtf8("pushButton13_3"))
        self.pushButton22_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton22_3.setGeometry(QtCore.QRect(160, 120, 10, 10))
        self.pushButton22_3.setText(_fromUtf8(""))
        self.pushButton22_3.setCheckable(True)
        self.pushButton22_3.setChecked(False)
        self.pushButton22_3.setAutoExclusive(False)
        self.pushButton22_3.setDefault(False)
        self.pushButton22_3.setFlat(False)
        self.pushButton22_3.setObjectName(_fromUtf8("pushButton22_3"))
        self.pushButton21_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton21_3.setGeometry(QtCore.QRect(100, 120, 10, 10))
        self.pushButton21_3.setText(_fromUtf8(""))
        self.pushButton21_3.setCheckable(True)
        self.pushButton21_3.setChecked(False)
        self.pushButton21_3.setAutoExclusive(False)
        self.pushButton21_3.setDefault(False)
        self.pushButton21_3.setFlat(False)
        self.pushButton21_3.setObjectName(_fromUtf8("pushButton21_3"))
        self.pushButton23_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton23_4.setGeometry(QtCore.QRect(170, 120, 10, 10))
        self.pushButton23_4.setText(_fromUtf8(""))
        self.pushButton23_4.setCheckable(True)
        self.pushButton23_4.setChecked(False)
        self.pushButton23_4.setAutoExclusive(False)
        self.pushButton23_4.setDefault(False)
        self.pushButton23_4.setFlat(False)
        self.pushButton23_4.setObjectName(_fromUtf8("pushButton23_4"))
        self.pushButton16_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton16_3.setGeometry(QtCore.QRect(150, 110, 10, 10))
        self.pushButton16_3.setText(_fromUtf8(""))
        self.pushButton16_3.setCheckable(True)
        self.pushButton16_3.setChecked(False)
        self.pushButton16_3.setAutoExclusive(False)
        self.pushButton16_3.setDefault(False)
        self.pushButton16_3.setFlat(False)
        self.pushButton16_3.setObjectName(_fromUtf8("pushButton16_3"))
        self.pushButton14_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton14_3.setGeometry(QtCore.QRect(130, 100, 10, 10))
        self.pushButton14_3.setText(_fromUtf8(""))
        self.pushButton14_3.setCheckable(True)
        self.pushButton14_3.setChecked(False)
        self.pushButton14_3.setAutoExclusive(False)
        self.pushButton14_3.setDefault(False)
        self.pushButton14_3.setFlat(False)
        self.pushButton14_3.setObjectName(_fromUtf8("pushButton14_3"))
        self.pushButton12_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton12_4.setGeometry(QtCore.QRect(110, 100, 10, 10))
        self.pushButton12_4.setText(_fromUtf8(""))
        self.pushButton12_4.setCheckable(True)
        self.pushButton12_4.setChecked(False)
        self.pushButton12_4.setAutoExclusive(False)
        self.pushButton12_4.setDefault(False)
        self.pushButton12_4.setFlat(False)
        self.pushButton12_4.setObjectName(_fromUtf8("pushButton12_4"))
        self.pushButton5_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton5_3.setGeometry(QtCore.QRect(190, 80, 10, 10))
        self.pushButton5_3.setText(_fromUtf8(""))
        self.pushButton5_3.setCheckable(True)
        self.pushButton5_3.setChecked(False)
        self.pushButton5_3.setAutoExclusive(False)
        self.pushButton5_3.setDefault(False)
        self.pushButton5_3.setFlat(False)
        self.pushButton5_3.setObjectName(_fromUtf8("pushButton5_3"))
        self.pushButton17_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton17_4.setGeometry(QtCore.QRect(160, 110, 10, 10))
        self.pushButton17_4.setText(_fromUtf8(""))
        self.pushButton17_4.setCheckable(True)
        self.pushButton17_4.setChecked(False)
        self.pushButton17_4.setAutoExclusive(False)
        self.pushButton17_4.setDefault(False)
        self.pushButton17_4.setFlat(False)
        self.pushButton17_4.setObjectName(_fromUtf8("pushButton17_4"))
        self.pushButton13_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton13_4.setGeometry(QtCore.QRect(170, 100, 10, 10))
        self.pushButton13_4.setText(_fromUtf8(""))
        self.pushButton13_4.setCheckable(True)
        self.pushButton13_4.setChecked(False)
        self.pushButton13_4.setAutoExclusive(False)
        self.pushButton13_4.setDefault(False)
        self.pushButton13_4.setFlat(False)
        self.pushButton13_4.setObjectName(_fromUtf8("pushButton13_4"))
        self.pushButton10_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton10_3.setGeometry(QtCore.QRect(190, 90, 10, 10))
        self.pushButton10_3.setText(_fromUtf8(""))
        self.pushButton10_3.setCheckable(True)
        self.pushButton10_3.setChecked(False)
        self.pushButton10_3.setAutoExclusive(False)
        self.pushButton10_3.setDefault(False)
        self.pushButton10_3.setFlat(False)
        self.pushButton10_3.setObjectName(_fromUtf8("pushButton10_3"))
        self.pushButton25_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton25_3.setGeometry(QtCore.QRect(140, 120, 10, 10))
        self.pushButton25_3.setText(_fromUtf8(""))
        self.pushButton25_3.setCheckable(True)
        self.pushButton25_3.setChecked(False)
        self.pushButton25_3.setAutoExclusive(False)
        self.pushButton25_3.setDefault(False)
        self.pushButton25_3.setFlat(False)
        self.pushButton25_3.setObjectName(_fromUtf8("pushButton25_3"))
        self.pushButton10_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton10_4.setGeometry(QtCore.QRect(140, 90, 10, 10))
        self.pushButton10_4.setText(_fromUtf8(""))
        self.pushButton10_4.setCheckable(True)
        self.pushButton10_4.setChecked(False)
        self.pushButton10_4.setAutoExclusive(False)
        self.pushButton10_4.setDefault(False)
        self.pushButton10_4.setFlat(False)
        self.pushButton10_4.setObjectName(_fromUtf8("pushButton10_4"))
        self.pushButton7_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton7_4.setGeometry(QtCore.QRect(160, 90, 10, 10))
        self.pushButton7_4.setText(_fromUtf8(""))
        self.pushButton7_4.setCheckable(True)
        self.pushButton7_4.setChecked(False)
        self.pushButton7_4.setAutoExclusive(False)
        self.pushButton7_4.setDefault(False)
        self.pushButton7_4.setFlat(False)
        self.pushButton7_4.setObjectName(_fromUtf8("pushButton7_4"))
        self.pushButton4_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton4_3.setGeometry(QtCore.QRect(130, 80, 10, 10))
        self.pushButton4_3.setText(_fromUtf8(""))
        self.pushButton4_3.setCheckable(True)
        self.pushButton4_3.setChecked(False)
        self.pushButton4_3.setAutoExclusive(False)
        self.pushButton4_3.setDefault(False)
        self.pushButton4_3.setFlat(False)
        self.pushButton4_3.setObjectName(_fromUtf8("pushButton4_3"))
        self.pushButton19_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton19_3.setGeometry(QtCore.QRect(180, 110, 10, 10))
        self.pushButton19_3.setText(_fromUtf8(""))
        self.pushButton19_3.setCheckable(True)
        self.pushButton19_3.setChecked(False)
        self.pushButton19_3.setAutoExclusive(False)
        self.pushButton19_3.setDefault(False)
        self.pushButton19_3.setFlat(False)
        self.pushButton19_3.setObjectName(_fromUtf8("pushButton19_3"))
        self.pushButton4_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton4_4.setGeometry(QtCore.QRect(180, 80, 10, 10))
        self.pushButton4_4.setText(_fromUtf8(""))
        self.pushButton4_4.setCheckable(True)
        self.pushButton4_4.setChecked(False)
        self.pushButton4_4.setAutoExclusive(False)
        self.pushButton4_4.setDefault(False)
        self.pushButton4_4.setFlat(False)
        self.pushButton4_4.setObjectName(_fromUtf8("pushButton4_4"))
        self.pushButton1_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton1_4.setGeometry(QtCore.QRect(100, 80, 10, 10))
        self.pushButton1_4.setText(_fromUtf8(""))
        self.pushButton1_4.setCheckable(True)
        self.pushButton1_4.setChecked(False)
        self.pushButton1_4.setAutoExclusive(False)
        self.pushButton1_4.setAutoDefault(False)
        self.pushButton1_4.setDefault(False)
        self.pushButton1_4.setFlat(False)
        self.pushButton1_4.setObjectName(_fromUtf8("pushButton1_4"))
        self.pushButton3_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton3_3.setGeometry(QtCore.QRect(170, 80, 10, 10))
        self.pushButton3_3.setText(_fromUtf8(""))
        self.pushButton3_3.setCheckable(True)
        self.pushButton3_3.setChecked(False)
        self.pushButton3_3.setAutoExclusive(False)
        self.pushButton3_3.setDefault(False)
        self.pushButton3_3.setFlat(False)
        self.pushButton3_3.setObjectName(_fromUtf8("pushButton3_3"))
        self.pushButton6_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton6_4.setGeometry(QtCore.QRect(100, 90, 10, 10))
        self.pushButton6_4.setText(_fromUtf8(""))
        self.pushButton6_4.setCheckable(True)
        self.pushButton6_4.setChecked(False)
        self.pushButton6_4.setAutoExclusive(False)
        self.pushButton6_4.setDefault(False)
        self.pushButton6_4.setFlat(False)
        self.pushButton6_4.setObjectName(_fromUtf8("pushButton6_4"))
        self.pushButton9_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton9_3.setGeometry(QtCore.QRect(130, 90, 10, 10))
        self.pushButton9_3.setText(_fromUtf8(""))
        self.pushButton9_3.setCheckable(True)
        self.pushButton9_3.setChecked(False)
        self.pushButton9_3.setAutoExclusive(False)
        self.pushButton9_3.setDefault(False)
        self.pushButton9_3.setFlat(False)
        self.pushButton9_3.setObjectName(_fromUtf8("pushButton9_3"))
        self.pushButton21_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton21_4.setGeometry(QtCore.QRect(150, 120, 10, 10))
        self.pushButton21_4.setText(_fromUtf8(""))
        self.pushButton21_4.setCheckable(True)
        self.pushButton21_4.setChecked(False)
        self.pushButton21_4.setAutoExclusive(False)
        self.pushButton21_4.setDefault(False)
        self.pushButton21_4.setFlat(False)
        self.pushButton21_4.setObjectName(_fromUtf8("pushButton21_4"))
        self.pushButton2_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton2_4.setGeometry(QtCore.QRect(110, 80, 10, 10))
        self.pushButton2_4.setText(_fromUtf8(""))
        self.pushButton2_4.setCheckable(True)
        self.pushButton2_4.setChecked(False)
        self.pushButton2_4.setAutoExclusive(False)
        self.pushButton2_4.setDefault(False)
        self.pushButton2_4.setFlat(False)
        self.pushButton2_4.setObjectName(_fromUtf8("pushButton2_4"))
        self.pushButton11_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton11_4.setGeometry(QtCore.QRect(150, 100, 10, 10))
        self.pushButton11_4.setText(_fromUtf8(""))
        self.pushButton11_4.setCheckable(True)
        self.pushButton11_4.setChecked(False)
        self.pushButton11_4.setAutoExclusive(False)
        self.pushButton11_4.setDefault(False)
        self.pushButton11_4.setFlat(False)
        self.pushButton11_4.setObjectName(_fromUtf8("pushButton11_4"))
        self.pushButton18_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton18_4.setGeometry(QtCore.QRect(170, 110, 10, 10))
        self.pushButton18_4.setText(_fromUtf8(""))
        self.pushButton18_4.setCheckable(True)
        self.pushButton18_4.setChecked(False)
        self.pushButton18_4.setAutoExclusive(False)
        self.pushButton18_4.setDefault(False)
        self.pushButton18_4.setFlat(False)
        self.pushButton18_4.setObjectName(_fromUtf8("pushButton18_4"))
        self.pushButton19_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton19_4.setGeometry(QtCore.QRect(130, 110, 10, 10))
        self.pushButton19_4.setText(_fromUtf8(""))
        self.pushButton19_4.setCheckable(True)
        self.pushButton19_4.setChecked(False)
        self.pushButton19_4.setAutoExclusive(False)
        self.pushButton19_4.setDefault(False)
        self.pushButton19_4.setFlat(False)
        self.pushButton19_4.setObjectName(_fromUtf8("pushButton19_4"))
        self.pushButton16_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton16_4.setGeometry(QtCore.QRect(100, 110, 10, 10))
        self.pushButton16_4.setText(_fromUtf8(""))
        self.pushButton16_4.setCheckable(True)
        self.pushButton16_4.setChecked(False)
        self.pushButton16_4.setAutoExclusive(False)
        self.pushButton16_4.setDefault(False)
        self.pushButton16_4.setFlat(False)
        self.pushButton16_4.setObjectName(_fromUtf8("pushButton16_4"))
        self.pushButton8_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton8_4.setGeometry(QtCore.QRect(170, 90, 10, 10))
        self.pushButton8_4.setText(_fromUtf8(""))
        self.pushButton8_4.setCheckable(True)
        self.pushButton8_4.setChecked(False)
        self.pushButton8_4.setAutoExclusive(False)
        self.pushButton8_4.setDefault(False)
        self.pushButton8_4.setFlat(False)
        self.pushButton8_4.setObjectName(_fromUtf8("pushButton8_4"))
        self.pushButton14_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton14_4.setGeometry(QtCore.QRect(180, 100, 10, 10))
        self.pushButton14_4.setText(_fromUtf8(""))
        self.pushButton14_4.setCheckable(True)
        self.pushButton14_4.setChecked(False)
        self.pushButton14_4.setAutoExclusive(False)
        self.pushButton14_4.setDefault(False)
        self.pushButton14_4.setFlat(False)
        self.pushButton14_4.setObjectName(_fromUtf8("pushButton14_4"))
        self.pushButton24_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton24_4.setGeometry(QtCore.QRect(180, 120, 10, 10))
        self.pushButton24_4.setText(_fromUtf8(""))
        self.pushButton24_4.setCheckable(True)
        self.pushButton24_4.setChecked(False)
        self.pushButton24_4.setAutoExclusive(False)
        self.pushButton24_4.setDefault(False)
        self.pushButton24_4.setFlat(False)
        self.pushButton24_4.setObjectName(_fromUtf8("pushButton24_4"))
        self.pushButton22_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton22_4.setGeometry(QtCore.QRect(110, 120, 10, 10))
        self.pushButton22_4.setText(_fromUtf8(""))
        self.pushButton22_4.setCheckable(True)
        self.pushButton22_4.setChecked(False)
        self.pushButton22_4.setAutoExclusive(False)
        self.pushButton22_4.setDefault(False)
        self.pushButton22_4.setFlat(False)
        self.pushButton22_4.setObjectName(_fromUtf8("pushButton22_4"))
        self.pushButton15_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton15_4.setGeometry(QtCore.QRect(190, 100, 10, 10))
        self.pushButton15_4.setText(_fromUtf8(""))
        self.pushButton15_4.setCheckable(True)
        self.pushButton15_4.setChecked(False)
        self.pushButton15_4.setAutoExclusive(False)
        self.pushButton15_4.setAutoDefault(False)
        self.pushButton15_4.setDefault(False)
        self.pushButton15_4.setFlat(False)
        self.pushButton15_4.setObjectName(_fromUtf8("pushButton15_4"))
        self.pushButton3_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton3_4.setGeometry(QtCore.QRect(120, 80, 10, 10))
        self.pushButton3_4.setText(_fromUtf8(""))
        self.pushButton3_4.setCheckable(True)
        self.pushButton3_4.setChecked(False)
        self.pushButton3_4.setAutoExclusive(False)
        self.pushButton3_4.setDefault(False)
        self.pushButton3_4.setFlat(False)
        self.pushButton3_4.setObjectName(_fromUtf8("pushButton3_4"))
        self.pushButton25_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton25_4.setGeometry(QtCore.QRect(190, 120, 10, 10))
        self.pushButton25_4.setText(_fromUtf8(""))
        self.pushButton25_4.setCheckable(True)
        self.pushButton25_4.setChecked(False)
        self.pushButton25_4.setAutoExclusive(False)
        self.pushButton25_4.setDefault(False)
        self.pushButton25_4.setFlat(False)
        self.pushButton25_4.setObjectName(_fromUtf8("pushButton25_4"))
        self.pushButton20_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton20_4.setGeometry(QtCore.QRect(140, 110, 10, 10))
        self.pushButton20_4.setText(_fromUtf8(""))
        self.pushButton20_4.setCheckable(True)
        self.pushButton20_4.setChecked(False)
        self.pushButton20_4.setAutoExclusive(False)
        self.pushButton20_4.setDefault(False)
        self.pushButton20_4.setFlat(False)
        self.pushButton20_4.setObjectName(_fromUtf8("pushButton20_4"))
        self.pushButton5_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton5_4.setGeometry(QtCore.QRect(140, 80, 10, 10))
        self.pushButton5_4.setText(_fromUtf8(""))
        self.pushButton5_4.setCheckable(True)
        self.pushButton5_4.setChecked(False)
        self.pushButton5_4.setAutoExclusive(False)
        self.pushButton5_4.setDefault(False)
        self.pushButton5_4.setFlat(False)
        self.pushButton5_4.setObjectName(_fromUtf8("pushButton5_4"))
        self.pushButton9_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton9_4.setGeometry(QtCore.QRect(180, 90, 10, 10))
        self.pushButton9_4.setText(_fromUtf8(""))
        self.pushButton9_4.setCheckable(True)
        self.pushButton9_4.setChecked(False)
        self.pushButton9_4.setAutoExclusive(False)
        self.pushButton9_4.setDefault(False)
        self.pushButton9_4.setFlat(False)
        self.pushButton9_4.setObjectName(_fromUtf8("pushButton9_4"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton4, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton4.setChecked)
        QtCore.QObject.connect(self.pushButton5, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton5.setChecked)
        QtCore.QObject.connect(self.pushButton6, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton6.setChecked)
        QtCore.QObject.connect(self.pushButton7, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton7.setChecked)
        QtCore.QObject.connect(self.pushButton8, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton8.setChecked)
        QtCore.QObject.connect(self.pushButton9, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton9.setChecked)
        QtCore.QObject.connect(self.pushButton10, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton10.setChecked)
        QtCore.QObject.connect(self.pushButton11, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton11.setChecked)
        QtCore.QObject.connect(self.pushButton12, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton12.setChecked)
        QtCore.QObject.connect(self.pushButton13, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton13.setChecked)
        QtCore.QObject.connect(self.pushButton14, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton14.setChecked)
        QtCore.QObject.connect(self.pushButton15, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton15.setChecked)
        QtCore.QObject.connect(self.pushButton16, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton16.setChecked)
        QtCore.QObject.connect(self.pushButton17, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton17.setChecked)
        QtCore.QObject.connect(self.pushButton18, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton18.setChecked)
        QtCore.QObject.connect(self.pushButton19, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton19.setChecked)
        QtCore.QObject.connect(self.pushButton20, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton20.setChecked)
        QtCore.QObject.connect(self.pushButton21, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton21.setChecked)
        QtCore.QObject.connect(self.pushButton22, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton22.setChecked)
        QtCore.QObject.connect(self.pushButton23, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton23.setChecked)
        QtCore.QObject.connect(self.pushButton24, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton24.setChecked)
        QtCore.QObject.connect(self.pushButton25, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton25.setChecked)
        QtCore.QObject.connect(self.pushButton1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton1.setChecked)
        QtCore.QObject.connect(self.pushButton2, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton2.setChecked)
        QtCore.QObject.connect(self.pushButton3, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton3.setChecked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.nauka.setText(_translate("MainWindow", "Ucz się", None))
        self.zgaduj.setText(_translate("MainWindow", "OK", None))

